query ValuedDirection {
	sovValuedDirection {
		id
		intro
		text
		textInput
		image {
			...MediaFragment
		}
	}
}

query TakeCareOfYourself {
	sovTakeCareOfMyself {
		id
		intro
		categories {
			id
			title
		}
	}
}

query HomeAssignment {
	sovHomeAssignment {
		id
		intro
	}
}

query AssessViolence {
	sovAssessViolence {
		id
		intro
		sinceLastSession {
			id
			title
		}
		otherProblems {
			id
			title
		}
	}
}

query Sork {
	sovSork {
		id
		categories {
			id
			title
			text
		}
	}
}

query SoundExercise {
	sovSoundExercise {
		id
		intro
		exercises {
			id
			title
			file {
				filename
				url
			}
			youtube {
				thumbnailUrl
				url
				title
				providerUid
				provider
			}
		}
	}
}
